### ISSUE TITLE
bandgap_1v_v01 Testing Plan

### ISSUE THREAD

**Issue by curtisma** [cascode-labs/bandgapReferenceCircuit#2]
### Tasks
- [x] #3
- [ ] #4
- [ ] Update the DC Op post-processing and Pytest tests
- [ ] #5
  -  Test out the existing design over full performance temperature range: -30c to 85c
- [ ] Create the stability test bench
  - Simulate the stability of the amplifier stand-alone
- [ ] Test out the existing design over all corners including the plot FS and SF corners
- [ ] Update the rest of the analyses data analysis to run as a set of Pytest tests
