### ISSUE TITLE
Reorganize the schematics to make them hierarchical

### ISSUE THREAD

**Issue by curtisma** [cascode-labs/bandgapReferenceCircuit#3]
### Description
We should have 2 levels of hierachy:
1. amplifier (lowest level)
2. bandgap (top level)

Then the bandgap instantiates the amp as shown below (still needs to be cleaned up)
![image](https://user-images.githubusercontent.com/4685385/229296083-4c1252e4-deb9-4ba5-b966-3042057e7a56.png)

We have a start but both need to be updated to fix their ports and to check netlisting and simulation.

### Tasks
- [x] 1. Update cell names as the file names
   - "amplifier_v01"
   - "bandgap_1v_v01"
- [x] 2. Update "amplifier_v01" schematic
- [x] 3. Check amp netlisting
- [x] 4. Check amp simulation using a DC Op sim
- [x] 5. Update the "bandgap_v01" schematic
- [x] 6. Check bandgap netlisting
- [x] 7. Check amplifier simulation using a DC Op sim

**Comment by curtisma** [comment]
Thanks @dengyulin01 and @ThomasPluck !
